version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16  # Use a compatible Node.js version
    working_directory: ~/repo

jobs:
  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Node.js dependencies
          command: |
            npm install
      - run:
          name: Run ESLint
          command: |
            npm run lint  # Replace with your ESLint command
      - run:
          name: Run tests
          command: |
            npm test  # Replace with your test command for React (e.g., npm run test)

workflows:
  version: 2
  test:
    jobs:
      - test
